CREDIT_SUPPORTERS = {
    "Saul",
    "Ellie",
    "Lyrae",
    "Sophia",
    "maemae",
    "charity",
    "Yuyake",
    "VioletArts",
    "Nope208",
    "Jack Black",
    "GRAND DAD",
    "Key's Artworks",
    "Kale!",
    "Mori",
    "milk",
    "Konata K.",
    "Gamebun",
    "Mama Moon",
    "上善若",
    "noise",
    "脚滑裤衩",
    "没78大蛇"
}